#!/usr/bin/env bash
# =============================================================================
# The website's buttons must lead somewhere.
#
# WHY THIS EXISTS
#
# Every call to action on site/index.html used to be `href="#pricing"` or
# `href="#trial"` — anchors on the page the visitor was already reading. "Start
# free trial" scrolled them down. There was no way to sign in. There was no
# download, because the Windows installer only existed as a CI artifact behind a
# GitHub login.
#
# That is not a bug a browser reports and not one a unit test notices: the page
# renders perfectly and every link works. It is only wrong if you know where the
# buttons were supposed to go.
#
# So this asserts the wiring exists:
#
#   * every route wire.js knows about is used by at least one button, and every
#     data-app value in the HTML is a route wire.js knows — a typo'd
#     data-app="signn" silently falls back to "/" and lands on the app's home
#     page, which for a signed-out visitor is a login screen that looks right and
#     is not what the button said;
#   * the download section exists with the ids wire.js writes into;
#   * config.js has every key wire.js reads, so a new setting cannot be read
#     before it is documented;
#   * NOTHING in site/ contains a Supabase key other than the anon one, judged
#     by decoding the token rather than by the shape of a JWT
#     rather than on the word "service_role" — the first version of that check
#     failed on config.js's own comment saying never to put one there.
#
# Usage:  bash supabase/check-site-links.sh      (no database needed)
# =============================================================================
set -uo pipefail
cd "$(dirname "$0")/.."

# ONE PAGE BECAME FIFTEEN, and every check below was written against one file.
#
# data-app buttons are now in the shared nav, footer and action bar, so they
# appear on every page; the download ids moved to their own page. Checking only
# site/index.html would have passed a typo'd data-app on any of the other
# fourteen. PAGES is every built page, the handbook excluded because it is
# generated by a different script and carries none of these hooks.
PAGES=$(ls site/*.html site/guides/*.html 2>/dev/null | grep -v '^site/guide\.html$')
HTML=site/index.html
DOWNLOAD=site/download.html
WIRE=site/wire.js
CONF=site/config.js
fail=0

if [ -z "$PAGES" ]; then
  echo "REFUSING TO REPORT SUCCESS: no built pages in site/. Run python3 scripts/build-site.py" >&2
  exit 1
fi
for f in "$HTML" "$DOWNLOAD" "$WIRE" "$CONF"; do
  [ -f "$f" ] || { echo "  missing: $f"; fail=1; }
done
[ "$fail" = 1 ] && { echo "::error::the website is missing files it needs"; exit 1; }

# --- 1. data-app values on both sides must agree -----------------------------
# ROUTES in wire.js is the authority. Extracted rather than duplicated here: a
# third copy of the list would be a third thing to keep in step.
routes=$(sed -n 's/.*var ROUTES = {\(.*\)}.*/\1/p' "$WIRE" \
         | tr ',' '\n' | sed -E 's/^[[:space:]]*([a-z]+):.*/\1/' | sed '/^$/d' | sort -u)
used=$(grep -oh 'data-app="[a-z]*"' $PAGES | sed 's/data-app="//; s/"//' | sort -u)

if [ -z "$routes" ]; then
  echo "REFUSING TO REPORT SUCCESS: could not read ROUTES out of $WIRE" >&2
  exit 1
fi
if [ -z "$used" ]; then
  echo "  no button on the site points into the app at all (no data-app attributes)"
  fail=1
fi

# A data-app the router does not know falls back to "/" — a link that looks
# right and goes to the wrong place, which is worse than one that is obviously
# broken.
for u in $used; do
  echo "$routes" | grep -qx "$u" \
    || { echo "  a page has data-app=\"$u\" and wire.js has no route for it"; fail=1; }
done

# The four the design promised. A route defined and never used is dead code on a
# marketing page, which is where dead code is least likely to be noticed.
for r in signin signup billing portal; do
  echo "$used" | grep -qx "$r" \
    || { echo "  nothing on the site links to \"$r\" — that path is still unreachable"; fail=1; }
done

# --- 2. the download section, and the ids wire.js writes into ---------------
# On the download PAGE, not the home page.
for id in download-box download-btn download-meta download-sha download-notes; do
  grep -q "id=\"$id\"" "$DOWNLOAD" \
    || { echo "  $HTML has no element with id=\"$id\", which wire.js writes the release into"; fail=1; }
done
grep -q 'id="download"' "$DOWNLOAD" \
  || { echo "  site/download.html has no #download section"; fail=1; }
# And the route to it must be the page, not the old in-page anchor. wire.js
# hides and unhides these by selector, so a stale '#download' href means the
# footer entry stays hidden for ever, including after a release is published.
if grep -qh 'href="#download"' $PAGES; then
  echo "  a page still links to the old #download anchor; it is a page now, so the"
  echo "  href must be /download or wire.js can never reveal it"
  fail=1
fi
grep -qh 'href="/download"' $PAGES \
  || { echo "  nothing links to /download, so a published installer would be unreachable"; fail=1; }

# --- 3. every setting wire.js reads is in config.js -------------------------
keys=$(grep -oE 'C\.[A-Z_]+' "$WIRE" | sed 's/^C\.//' | sort -u)
for k in $keys; do
  grep -q "$k" "$CONF" \
    || { echo "  wire.js reads $k and config.js does not document it"; fail=1; }
done

# --- 4. no KEY has been pasted into a static file --------------------------
# Matched on the SHAPE OF A VALUE, not on the word "service_role".
#
# The first version grepped for that word and failed on config.js's own comment
# telling you never to put it there — the guard reporting its own documentation
# as a breach, which is the same mistake check-readonly-writes.py made about a
# comment explaining why a function used has_role.
#
# A Supabase key is a JWT: three dot-separated base64url segments starting
# `eyJ`. This used to refuse ANY of them on shape alone, and its own message
# admitted it could not tell which key it had found: "And if it is the
# service_role key". It now decodes the payload and judges by the role inside,
# which makes it both stricter and quieter.
#
# WHY THE ANON KEY IS ALLOWED HERE, AND THIS IS A REVERSAL. The old rule said a
# committed key "is a thing you cannot take back". True, and it protects nothing
# in this case: the anon key and the project URL are compiled into web/dist by
# Vite and served to every browser that opens the app. Refusing the same two
# values in site/config.js while shipping them in the application bundle is not
# a security boundary, it is a rule that only bites the person deploying.
#
# And it bit. The marketing site has no build step of its own: scripts/build-site.py
# says in plain words that the deployment is a hand upload of site/ to
# Cloudflare. "Leave the defaults empty here" therefore meant editing config.js
# by hand after every build and before every upload, forever, from memory. The
# first time that is forgotten the live site's buttons read "not yet pointed at
# the software", which is the exact failure the rest of this file exists to
# prevent. A rule that has to be remembered on every deploy is a rule that will
# be broken on some deploy.
#
# THE SERVICE_ROLE KEY IS STILL REFUSED, and now refused BY NAME rather than by
# resemblance. That one bypasses every row-level rule in the database, and a
# file a browser can download must never contain it.
found_keys=$(grep -rlE 'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}' site/ 2>/dev/null || true)
if [ -n "$found_keys" ]; then
  bad_keys=$(python3 - "$found_keys" <<'PYEOF'
import base64, json, re, sys
pat = re.compile(r'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}')
bad = []
for path in sys.argv[1].split():
    try:
        text = open(path, encoding='utf-8', errors='replace').read()
    except OSError:
        continue
    for tok in pat.findall(text):
        seg = tok.split('.')[1]
        # base64url, and the padding is stripped in a JWT.
        seg += '=' * (-len(seg) % 4)
        try:
            claims = json.loads(base64.urlsafe_b64decode(seg).decode('utf-8'))
        except Exception:
            # Undecodable means it is not a key we can vouch for, so it is
            # named. Silence on a token we cannot read is the wrong default.
            bad.append(f'{path}: a token that could not be decoded')
            continue
        role = claims.get('role')
        if role != 'anon':
            bad.append(f'{path}: a key with role {role!r}')
print('\n'.join(bad))
PYEOF
)
  if [ -n "$bad_keys" ]; then
    echo "  a file in site/ contains a Supabase key that is not the anon key."
    echo "  The service_role key bypasses every row-level rule in the database and"
    echo "  must never reach a file a browser can download. Rotate it now if this"
    echo "  has been committed or deployed."
    printf '%s\n' "$bad_keys" | sed 's/^/    /'
    fail=1
  fi
fi

if [ "$fail" = 1 ]; then
  echo
  echo "::error::the website's links are not wired to the software"
  exit 1
fi

echo "site/: $(printf '%s\n' $PAGES | wc -l | tr -d ' ') pages link into the app for $(echo "$used" | tr '\n' ' ')with the download page present, config documented and no secrets"
